version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: user 
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: postgres_corgi
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
